name: SMoney
version: 1.0
main: com.yourname.smoney.Main
api-version: 1.21

commands:
  money:
    description: Check or send money
    usage: /money
    permission: smoney.money

  shop:
    description: Open shop
    usage: /shop
    permission: smoney.shop

  quest:
    description: Open quest menu
    usage: /quest
    permission: smoney.quest

  market:
    description: Open market & trading system
    usage: /market help
    permission: smoney.market
    aliases: [m, ah]

permissions:
  smoney.money:
    default: true

  smoney.shop:
    default: true

  smoney.quest:
    default: true

  smoney.market:
    default: true

  smoney.admin:
    default: op